import {default as HistoryIcon} from './HistoryIcon';
import {default as EditIcon} from './EditIcon';
import {default as NotFound} from './NotFound';
import {default as ApartmentIcon} from './ApartmentIcon';
import {default as BusinessIcon} from './BusinessIcon';
import {default as UserSvgIcon} from './UserSvgIcon';
import {default as PaymentIcon} from './Payment';
import {default as ShoppingCartIcon} from './ShoppingCartIcon';
import {default as SalesIcon} from './SalesIcon';
export {HistoryIcon, EditIcon, NotFound, ApartmentIcon, BusinessIcon, UserSvgIcon, PaymentIcon, ShoppingCartIcon, SalesIcon};